export const MODAL_MUTATIONS = {
  ADD_LAYERED_MODALS: 'ADD_LAYERED_MODALS'
}

export const ACCOUNT_MUTATIONS = {
  LOG_IN_USER: 'LOG_IN_USER',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  SET_LOCALE: 'SET_LOCALE'
}

export const BASE_MUTATIONS = {
  SET_APP_LOADING: 'SET_APP_LOADING'
}
